---
title: "FINAL PROJECT TITLE"
author: "REMEMBER TO OUR IDS IN HERE" 
date: "11/21/2016"
output: pdf_document
---

#[1] Set up libraries
```{r loadlibs, echo=FALSE, message=FALSE, warning=FALSE}
# Put all libraries here. 
library( texreg )
library( arm )
library( lme4 )
library( foreign )
library( plyr)
library( sqldf) 
library( foreign )
library( sqldf)
library( ggplot2 ) 
library( scales )
library( pander)
library( nlme)
library( lattice)
library( Hmisc)
   
# Put global display options here
options(digits=2)

# This flag is to control whether analytic code blocks should display
# the code itself.
# When turning in work, you should knit two pdfs, 
# with this variable set to FALSE and TRUE respectively.
# When FALSE you have a nice report with results only.  When TRUE you have 
# the code itself so we can see what you did.
show.code = FALSE
# show.code = TRUE # just comment this line out to make it false

# This controls whether the code for making plots should be shown.
# When turning in your work, you should leave this as FALSE, 
# unless there is something about your plots that is not working as it should.
show.plot.code = show.code
show.plot.code = FALSE #  comment this out to make it follow the overall config
```


#[2] Call in Data
```{r setup, include=FALSE}
#Call in IPEDS data
  #Stored in Vinh's Dropbox account
  #####MUST CONNECT TO INTERNET#####
IPEDS <-read.csv(file="https://dl.dropboxusercontent.com/u/4893048/compiled_ipeds_csv.csv", header=TRUE) 

str(IPEDS)
#20606 observations
#160 vars

#If calling data from a local folder, uncomment these 2 lines instead
#setwd("") #put working directory 
#IPEDS <- read.csv("compiled_ipeds_csv.csv")

``` 



#Put empty sections below just as templates

#[3]
```{r include=TRUE}
# Create dataset with complete cases
levels(IPEDS$level)
dat <- subset(IPEDS, IPEDS$level=="Four or more years")

newdat <- dat[complete.cases(dat$completeasiantot, dat$completeblacktot, dat$completenatamtot, 
                             dat$completehisptot, dat$completewhitetot, dat$completetot,
                             dat$enrolasiantot_ft, dat$enrolblacktot_ft, dat$enrolnatamtot_ft, 
                             dat$enrolhisptot_ft, dat$enrolwhitetot_ft, dat$enroltot_ft,
                             dat$enrolasiantot_pt, dat$enrolblacktot_pt, dat$enrolnatamtot_pt, 
                             dat$enrolhisotot_pt, dat$enrolwhitetot_pt, dat$enroltot_pt,
                             dat$unitid, dat$instname, dat$year, dat$state, dat$zip, 
                             dat$pct_stategrant, dat$pct_instgrant, dat$pct_fedgrant, dat$pct_loan, 
                             dat$stategrant_a, dat$instgrant_a, dat$fedgrant_a, dat$loan_a,
                             dat$satvr25, dat$satvr75, dat$satmt25, dat$satmt75, dat$admgpa,
                             dat$carnegieenrl, dat$carnegiebasic), ]

# Create main outcome variables
attach(newdat)
newdat$urmgrad <- 
  
  (newdat$completeblacktot + newdat$completenatamtot + newdat$completehisptot)/newdat$complettot

subset(newdat, persistblack==NA)
newdat[newdat$persistblack==NA,]
```

#[4]
```{r include=TRUE}

```

#[5]
```{r include=TRUE}

```

#[6]
```{r include=TRUE}

```

#[7]
```{r include=TRUE}

```

#[8]
```{r include=TRUE}

```



#This is test code
```{r include=FALSE}

#testing out a comment 

```
